### ISSUE TITLE
which version of SBCL can be used on Raspberry Pi 3?

### ISSUE THREAD

**Issue by muyinliu** [LaloHao/rpi-sbcl#1]

**Comment by LaloHao** [comment]
I believe the Pi3 comes with ARMhf support
http://www.sbcl.org/platform-table.html

You can find the package in official repositories if you use Arch Linux Arm
https://archlinuxarm.org/packages/armv7h/sbcl

**Comment by muyinliu** [comment]
Thanks. ARMhf version of SBCL(v1.3.12) works fine on RASPBIAN with my Pi3, but NOT support threads on RASPBIAN because RASPBIAN is 32-bit OS and SBCL's thread only support amd64.
